<a href="https://colab.research.google.com/github/simplysumanth/Tensorflow-ZTM/blob/main/00_Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.1


### Creating tensors with tf.constant

In [3]:
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [16]:
vector = tf.constant([3.,9.])
vector.ndim

1

In [26]:
matrix = tf.constant([[1.,2.],
                      [3.,4.]
                      ],dtype=tf.float32)
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [37]:

matrix = tf.constant([[1,2,3]],dtype=tf.float32)
matrix

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [39]:
tensor = tf.constant([[[1.,2.,3.],
                       [1.,2.,3.],
                       [1.,2.,3.]],
                       ])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]], dtype=float32)>

### Create tensors using tf.variable

In [41]:
changeable_tensor = tf.Variable(3.)
unchangeable_tensor = tf.constant(3.)
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>)