<a href="https://colab.research.google.com/github/simplysumanth/Tensorflow-ZTM/blob/main/00_Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.5.0


### Creating tensors with tf.constant

In [3]:
scalar = tf.constant(9)
scalar
#scalar.numpy()

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [4]:
vector = tf.constant([3.,9.])
vector.ndim
#vector.ndim

1

In [5]:
matrix = tf.constant([[1.,2.],
                      [3.,4.]
                      ],dtype=tf.float32)
matrix
#matrix.ndim

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [6]:

matrix = tf.constant([[1,2,3]],dtype=tf.float32)
matrix

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [7]:
tensor = tf.constant([[[1.,2.,3.],
                       [1.,2.,3.],
                       [1.,2.,3.]],
                       ])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]], dtype=float32)>

In [8]:
tensor.numpy()

array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]], dtype=float32)

### Create tensors using tf.variable

In [9]:
changeable_tensor = tf.Variable([3.,5.])
unchangeable_tensor = tf.constant(3.)
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>)

In [10]:
changeable_tensor[0] =7
changeable_tensor

TypeError: ignored

This gives an error: As we have to use assign() for assigning stuff to tf.variable()

In [11]:
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 5.], dtype=float32)>

#### Creating Random Tensors

In [12]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2)) #try (2,3)

random_1 , random_2 #as there is same seed, the values are same

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

##### Shuffling a tensor

In [13]:
not_shuffled = tf.constant([1,2,3])
not_shuffled

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [14]:
shuffled = tf.random.shuffle(not_shuffled,seed=42)
shuffled

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 1], dtype=int32)>

###### Creating tensors using numpy

In [15]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.float64)

t = tf.constant(numpy_A, shape=[2,3,4])
t

<tf.Tensor: shape=(2, 3, 4), dtype=float64, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])>

In [16]:
##Getting information from tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.shape(rank_4_tensor), tf.size(rank_4_tensor), tf.size(rank_4_tensor).numpy()

(4,
 TensorShape([2, 3, 4, 5]),
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 120)

##### tf.function()

In [18]:
@tf.function()
def return_some(a,b):
  return tf.argmax([a,b])

a = tf.constant([1])
b = tf.constant([4])

return_some(a,b).numpy()

array([1])

In [19]:
#reshape
reshaped = tf.reshape(tf.ones(shape=(4,4)),shape = (2,2,2,2))
reshaped , reshaped.ndim , reshaped.shape

(<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
 array([[[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]],
 
 
        [[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]], dtype=float32)>, 4, TensorShape([2, 2, 2, 2]))

In [20]:
##Access GPU
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [21]:
!nvidia-smi

Tue Jul 13 16:57:24 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    29W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [22]:
#1
vector = tf.constant([1,2])
scalar = tf.constant([1])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant([[[1,2,3],[2,3,4]],[[1,2,3],[5,6,7]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [5, 6, 7]]], dtype=int32)>

In [30]:
#2
tensor.ndim,len(tensor.shape), tensor.shape

(3, 3, TensorShape([2, 2, 3]))

In [23]:
#3
tensor_1 = tf.random.uniform(minval=0,maxval=1,shape=(5,300))
tensor_1
#3 
tensor_2 = tf.random.uniform(minval=0,maxval=1,shape=(5,300))
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.4245448 , 0.9852921 , 0.22806215, ..., 0.99955857, 0.92019296,
        0.8754319 ],
       [0.92107344, 0.8982934 , 0.02503371, ..., 0.88536036, 0.91565335,
        0.29052258],
       [0.9666878 , 0.44125116, 0.9793072 , ..., 0.12928712, 0.90663266,
        0.7979338 ],
       [0.42861843, 0.9294132 , 0.06348825, ..., 0.8441986 , 0.18510687,
        0.6784674 ],
       [0.4883865 , 0.501001  , 0.9376265 , ..., 0.7131486 , 0.35771775,
        0.20938599]], dtype=float32)>

In [24]:
#4
tf.matmul(tensor_1,tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.176796, 74.40558 , 75.59343 , 76.54194 , 72.60106 ],
       [73.83435 , 71.431305, 69.95559 , 72.23826 , 74.000916],
       [76.10207 , 73.53424 , 71.993675, 74.605934, 72.3186  ],
       [72.14397 , 74.31719 , 71.40324 , 78.00717 , 73.68057 ],
       [70.15432 , 69.71037 , 70.52122 , 73.55441 , 71.40969 ]],
      dtype=float32)>

In [25]:
#optional
tensor_1 @ tf.transpose(tensor_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.176796, 74.40558 , 75.59343 , 76.54194 , 72.60106 ],
       [73.83435 , 71.431305, 69.95559 , 72.23826 , 74.000916],
       [76.10207 , 73.53424 , 71.993675, 74.605934, 72.3186  ],
       [72.14397 , 74.31719 , 71.40324 , 78.00717 , 73.68057 ],
       [70.15432 , 69.71037 , 70.52122 , 73.55441 , 71.40969 ]],
      dtype=float32)>

In [27]:
#5
tf.tensordot(tensor_1,tf.reshape(tensor_2,shape = (300,5)),axes= 1)


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.65602 , 76.459625, 74.62671 , 74.370476, 73.22405 ],
       [70.30267 , 74.453926, 76.463905, 73.37727 , 75.0737  ],
       [73.51926 , 74.47668 , 75.62335 , 69.02122 , 69.59264 ],
       [72.141106, 75.83377 , 78.76407 , 73.42118 , 72.769936],
       [71.28571 , 71.8942  , 75.47025 , 72.867165, 66.61007 ]],
      dtype=float32)>

In [33]:
#6
six = tf.random.uniform(minval=0,maxval=1, shape=(224, 224, 3))

In [36]:
#7
tf.reduce_min(six),tf.reduce_max(six)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.3841858e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999285>)

In [57]:
#8
eig= tf.random.uniform(shape=(1, 224, 224, 3))
print(eig.shape)
eig = tf.squeeze(eig)
print(eig.shape)

#optional -> squeeze it to single dim
re = tf.reshape(eig, shape = (-1))
re.shape


(1, 224, 224, 3)
(224, 224, 3)


TensorShape([150528])

In [48]:
#9
nine = tf.random.normal(shape=[10])
print(nine)
tf.argmax(nine).numpy()

tf.Tensor(
[ 0.6557662  -0.83798057 -1.112298   -0.02573727  1.1823075   1.6463572
 -0.26520288 -0.3747401   0.6220301  -1.3128812 ], shape=(10,), dtype=float32)


5

In [52]:
#10
ten = tf.one_hot(nine.numpy(),depth = 10)
ten

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>